# Generated by Django 4.2.16 on 2024-11-20 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriteproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='favoriteproduct',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='joinproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='joinproduct',
            old_name='user_id',
            new_name='user',
        ),
    ]
